

#include <bits/stdc++.h>
using namespace std;

struct MonotonicCHT {
    struct Line {
        long long m, c;
        long long eval(long long x) const { return m * x + c; }
    };
    
    deque<Line> dq;

    bool is_bad(const Line& l1, const Line& l2, const Line& l3) {
        return (__int128)(l3.c - l1.c) * (l1.m - l2.m) <= 
               (__int128)(l2.c - l1.c) * (l1.m - l3.m);
    }

    void add(long long m, long long c) {
        Line l = {m, c};
        while (dq.size() >= 2 && is_bad(dq[dq.size() - 2], dq.back(), l)) {
            dq.pop_back();
        }
        dq.push_back(l);
    }

    long long query(long long x) {
        while (dq.size() >= 2 && dq[0].eval(x) <= dq[1].eval(x)) {
            dq.pop_front();
        }
        return dq[0].eval(x);
    }
};

int main() {
    ios_base::sync_with_stdio(false);
    cin.tie(NULL);

    int n;
    long long C;
    if (!(cin >> n >> C)) return 0;

    vector<long long> h(n + 1);
    for (int i = 1; i <= n; i++) cin >> h[i];

    vector<long long> dp(n + 1, 0);
    MonotonicCHT cht;

    // Base Case: Stone 1
    dp[1] = 0;
    
    // Insert line for stone 1 using NEGATION TRICK (negate slope and intercept):
    // Original slope: -2*h[1], Original intercept: dp[1] + h[1]*h[1]
    cht.add(2 * h[1], -(dp[1] + h[1] * h[1]));

    for (int i = 2; i <= n; i++) {
        // Query the minimum using negation trick:
        long long min_line_val = -cht.query(h[i]);
        
        // Complete the recurrence:
        dp[i] = h[i] * h[i] + C + min_line_val;

        // Add the new line generated by state i to the CHT:
        cht.add(2 * h[i], -(dp[i] + h[i] * h[i]));
    }

    cout << dp[n] << "\n";
    return 0;
}
